import './globals.css'
import { Roboto } from 'next/font/google'
import Header from "@/app/components/header";
import React from "react";
import Footer from "@/app/components/footer";

const roboto = Roboto({weight: '400', subsets: ['latin'] })

export const metadata = {
  title: 'Shanta Next Gen App',
  description: 'Generated by Asiq',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">

    <body className={roboto.className}><Header/>{children}<Footer/></body>

    </html>
  )
}
